### PR TITLE
chore: change travis to run nodejs 6, 8 and 10

### PR DESCRIPTION
**Pull request by kuba-kubula**

### CODE REVIEW

**Review by dariagrudzien — APPROVED** [review]
🚀

**Comment by honzajavorek** [comment]
This is an open source library where dropping Node versions is a breaking change. I don't see semantic release around, but the next version should be major bump.

**Comment by kuba-kubula** [comment]
@honzajavorek Supporting NodeJS below 6 is discouraged even from the authors of NodeJS nowadays, but you're right in a way this library deserves a proper release, some-day in future.

Except, its code haven't changed at all since last OAS3–identifying came into the house.

I'll make a release then with `1.0.0` 🎉

**Comment by honzajavorek** [comment]
Dropping Node 6 is definitely a good step, I just noted it should result in a version bump when releasing. I'm not sure how this gets released, I think it is mostly in AD team's realm.

**Comment by kuba-kubula** [comment]
@honzajavorek already released for ~24 hours now

**Pull request merged**
