### PR TITLE
Handle empty input

### PR DESCRIPTION
**Pull request by honzajavorek**
Close https://github.com/apiaryio/deckardcain/issues/25

### CODE REVIEW

**Comment by honzajavorek** [comment]
@kylef Does it make any sense to revive and merge this?

**Comment by kylef** [comment]
@honzajavorek I am not sure. This PR is to project against undefined/null as input causing deckard cain to raise exception? If that's a problem then go for it 😃.

**Comment by honzajavorek** [comment]
> If that's a problem

I don't know 😃 I don't recall the original motivation. I was hoping perhaps you know whether this was already addressed or not.

**Comment by honzajavorek** [comment]
Ah, reading code, it is still relevant it seems.

**Pull request closed without merging**
